### ISSUE TITLE
How to manage application's state when using  `Relay`?

### ISSUE THREAD

**Issue by zwl1619** [kikoseijo/react-relay-app#1]
`Apollo` manages application's state with `apollo-link-state`,what about `Relay`?

**Comment by kikoseijo** [comment]
Sorry, i have only 1 week experience on relay, and haven't tried apollo, anyone?

**Comment by fernandocalsa** [comment]
I have been working with Relay for some time, and I tried to use Relay Store to manage the application state. I created a GraphQL "server" into the front end with the application state, for example a settings type with a language field. Then I had to mix the frontend schema with the actual graphQL schema and run the relay compile.

After a month working like that we realised that is hard to manage the app state in this way. So we are starting to implement Redux, so we will use Relay for server data, and Redux for application state like language selected. We have just started so I can't give you a clear output, but I am happy with how we are managing it and I believe this is going to work fine.

Please, share your thoughts and any other approach :)

**Comment by kikoseijo** [comment]
From my perspective, as we dealing with poor information about, Relay got access to local storage, this where they keep things requested from server.
Can we not make mutations into there where no network request needed? @fernandocalsa 

Setup a server to do state management its an approach that personally will never go for, unless, lets think of a bigger perspective, app state management its done server side and we can even spread app state across devices, Is this the Relay concept?
 
In my use case, network call are very cheap, offline state could be tricky, but I think its also posible.
